#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package pyrods
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "pyrods"
pkg_ver = "2.4.1"
PREFIX  = pjoin(env['SIT_EXTERNAL_SW'], "PyRods", pkg_ver)
PYDIR = pjoin(env['LIB_ABI'], env['PYTHON'], "site-packages")

standardExternalPackage ( pkg, **locals() )
