#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package pyrods
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any LUSI project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "pyrods"
pkg_ver = "2.3.0"
PREFIX  = pjoin(env['LUSI_ROOT'],"sw/external/PyRods",pkg_ver)

PYDIR = "lib"
if env['LUSI_ARCH_PROC'] == 'x86_64' : PYDIR = "lib64"
PYDIR += "/python"+env['PYTHON_VERSION']+"/site-packages"

standardExternalPackage ( pkg, **locals() )
