#!/bin/sh

set -e

if [ ! -d psddldata/data/ ]; then
    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
    exit 1
fi

files=`ls -1 psddldata/data/*.ddl | grep -v xtc.ddl`

for f in $files ; do 
    psddlc -b psana -I data -E psddl_psana/include -O psddl_psana/src -i psddl_psana -t Psana $f
done
