/* Do not edit this file, as it is auto-generated */

#ifndef PSANA_PRINCETON_DDL_WRAPPER_H
#define PSANA_PRINCETON_DDL_WRAPPER_H 1

#include <vector>
#include <ndarray/ndarray.h>
#include <pdsdata/xtc/TypeId.hh>
#include <psddl_python/DdlWrapper.h>

namespace Psana {
namespace Princeton {

using namespace boost::python;
using boost::python::api::object;
using boost::shared_ptr;
using std::vector;

extern void createWrappers();

class ConfigV1_Wrapper {
  shared_ptr<ConfigV1> _o;
  ConfigV1* o;
public:
  enum { TypeId = Pds::TypeId::Id_PrincetonConfig };
  enum { Version = 1 };
  ConfigV1_Wrapper(shared_ptr<ConfigV1> obj) : _o(obj), o(_o.get()) {}
  ConfigV1_Wrapper(ConfigV1* obj) : o(obj) {}
  uint32_t width() const { return o->width(); }
  uint32_t height() const { return o->height(); }
  uint32_t orgX() const { return o->orgX(); }
  uint32_t orgY() const { return o->orgY(); }
  uint32_t binX() const { return o->binX(); }
  uint32_t binY() const { return o->binY(); }
  float exposureTime() const { return o->exposureTime(); }
  float coolingTemp() const { return o->coolingTemp(); }
  uint32_t readoutSpeedIndex() const { return o->readoutSpeedIndex(); }
  uint16_t readoutEventCode() const { return o->readoutEventCode(); }
  uint16_t delayMode() const { return o->delayMode(); }
  uint32_t frameSize() const { return o->frameSize(); }
  uint32_t numPixelsX() const { return o->numPixelsX(); }
  uint32_t numPixelsY() const { return o->numPixelsY(); }
  uint32_t numPixels() const { return o->numPixels(); }
};

class ConfigV2_Wrapper {
  shared_ptr<ConfigV2> _o;
  ConfigV2* o;
public:
  enum { TypeId = Pds::TypeId::Id_PrincetonConfig };
  enum { Version = 2 };
  ConfigV2_Wrapper(shared_ptr<ConfigV2> obj) : _o(obj), o(_o.get()) {}
  ConfigV2_Wrapper(ConfigV2* obj) : o(obj) {}
  uint32_t width() const { return o->width(); }
  uint32_t height() const { return o->height(); }
  uint32_t orgX() const { return o->orgX(); }
  uint32_t orgY() const { return o->orgY(); }
  uint32_t binX() const { return o->binX(); }
  uint32_t binY() const { return o->binY(); }
  float exposureTime() const { return o->exposureTime(); }
  float coolingTemp() const { return o->coolingTemp(); }
  uint16_t gainIndex() const { return o->gainIndex(); }
  uint16_t readoutSpeedIndex() const { return o->readoutSpeedIndex(); }
  uint16_t readoutEventCode() const { return o->readoutEventCode(); }
  uint16_t delayMode() const { return o->delayMode(); }
  uint32_t frameSize() const { return o->frameSize(); }
  uint32_t numPixelsX() const { return o->numPixelsX(); }
  uint32_t numPixelsY() const { return o->numPixelsY(); }
  uint32_t numPixels() const { return o->numPixels(); }
};

class ConfigV3_Wrapper {
  shared_ptr<ConfigV3> _o;
  ConfigV3* o;
public:
  enum { TypeId = Pds::TypeId::Id_PrincetonConfig };
  enum { Version = 3 };
  ConfigV3_Wrapper(shared_ptr<ConfigV3> obj) : _o(obj), o(_o.get()) {}
  ConfigV3_Wrapper(ConfigV3* obj) : o(obj) {}
  uint32_t width() const { return o->width(); }
  uint32_t height() const { return o->height(); }
  uint32_t orgX() const { return o->orgX(); }
  uint32_t orgY() const { return o->orgY(); }
  uint32_t binX() const { return o->binX(); }
  uint32_t binY() const { return o->binY(); }
  float exposureTime() const { return o->exposureTime(); }
  float coolingTemp() const { return o->coolingTemp(); }
  uint8_t gainIndex() const { return o->gainIndex(); }
  uint8_t readoutSpeedIndex() const { return o->readoutSpeedIndex(); }
  uint16_t exposureEventCode() const { return o->exposureEventCode(); }
  uint32_t numDelayShots() const { return o->numDelayShots(); }
  uint32_t frameSize() const { return o->frameSize(); }
  uint32_t numPixelsX() const { return o->numPixelsX(); }
  uint32_t numPixelsY() const { return o->numPixelsY(); }
  uint32_t numPixels() const { return o->numPixels(); }
};
class ConfigV1;
class ConfigV2;
class ConfigV3;

class FrameV1_Wrapper {
  shared_ptr<FrameV1> _o;
  FrameV1* o;
public:
  enum { TypeId = Pds::TypeId::Id_PrincetonFrame };
  enum { Version = 1 };
  FrameV1_Wrapper(shared_ptr<FrameV1> obj) : _o(obj), o(_o.get()) {}
  FrameV1_Wrapper(FrameV1* obj) : o(obj) {}
  uint32_t shotIdStart() const { return o->shotIdStart(); }
  float readoutTime() const { return o->readoutTime(); }
  PyObject* data() const { ND_CONVERT(o->data(), uint16_t, 2); }
};

class InfoV1_Wrapper {
  shared_ptr<InfoV1> _o;
  InfoV1* o;
public:
  enum { TypeId = Pds::TypeId::Id_PrincetonInfo };
  enum { Version = 1 };
  InfoV1_Wrapper(shared_ptr<InfoV1> obj) : _o(obj), o(_o.get()) {}
  InfoV1_Wrapper(InfoV1* obj) : o(obj) {}
  float temperature() const { return o->temperature(); }
  uint32_t _sizeof() const { return o->_sizeof(); }
};

  class ConfigV1_Getter : public Psana::EnvGetter {
  public:
    const std::type_info& getTypeInfo() {
      return typeid(Psana::Princeton::ConfigV1);
    }
    const char* getTypeName() {
      return "Psana::Princeton::ConfigV1";
    }
    int getTypeId() {
      return ConfigV1::TypeId;
    }
    int getVersion() {
      return ConfigV1::Version;
    }
    object get(PSEnv::EnvObjectStore& store, const PSEvt::Source& src, Pds::Src* foundSrc=0) {
      boost::shared_ptr<ConfigV1> result = store.get(src, 0);
      return result.get() ? object(ConfigV1_Wrapper(result)) : object();
    }
  };

  class ConfigV2_Getter : public Psana::EnvGetter {
  public:
    const std::type_info& getTypeInfo() {
      return typeid(Psana::Princeton::ConfigV2);
    }
    const char* getTypeName() {
      return "Psana::Princeton::ConfigV2";
    }
    int getTypeId() {
      return ConfigV2::TypeId;
    }
    int getVersion() {
      return ConfigV2::Version;
    }
    object get(PSEnv::EnvObjectStore& store, const PSEvt::Source& src, Pds::Src* foundSrc=0) {
      boost::shared_ptr<ConfigV2> result = store.get(src, 0);
      return result.get() ? object(ConfigV2_Wrapper(result)) : object();
    }
  };

  class ConfigV3_Getter : public Psana::EnvGetter {
  public:
    const std::type_info& getTypeInfo() {
      return typeid(Psana::Princeton::ConfigV3);
    }
    const char* getTypeName() {
      return "Psana::Princeton::ConfigV3";
    }
    int getTypeId() {
      return ConfigV3::TypeId;
    }
    int getVersion() {
      return ConfigV3::Version;
    }
    object get(PSEnv::EnvObjectStore& store, const PSEvt::Source& src, Pds::Src* foundSrc=0) {
      boost::shared_ptr<ConfigV3> result = store.get(src, 0);
      return result.get() ? object(ConfigV3_Wrapper(result)) : object();
    }
  };

  class FrameV1_Getter : public Psana::EvtGetter {
  public:
    const std::type_info& getTypeInfo() {
      return typeid(Psana::Princeton::FrameV1);
    }
    const char* getTypeName() {
      return "Psana::Princeton::FrameV1";
    }
    int getTypeId() {
      return FrameV1::TypeId;
    }
    int getVersion() {
      return FrameV1::Version;
    }
    object get(PSEvt::Event& evt, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<FrameV1> result = evt.get(key, foundSrc);
      return result.get() ? object(FrameV1_Wrapper(result)) : object();
    }
    object get(PSEvt::Event& evt, Pds::Src& src, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<FrameV1> result = evt.get(src, key, foundSrc);
      return result.get() ? object(FrameV1_Wrapper(result)) : object();
    }
    object get(PSEvt::Event& evt, PSEvt::Source& source, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<FrameV1> result = evt.get(source, key, foundSrc);
      return result.get() ? object(FrameV1_Wrapper(result)) : object();
    }
  };

  class InfoV1_Getter : public Psana::EvtGetter {
  public:
    const std::type_info& getTypeInfo() {
      return typeid(Psana::Princeton::InfoV1);
    }
    const char* getTypeName() {
      return "Psana::Princeton::InfoV1";
    }
    int getTypeId() {
      return InfoV1::TypeId;
    }
    int getVersion() {
      return InfoV1::Version;
    }
    object get(PSEvt::Event& evt, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<InfoV1> result = evt.get(key, foundSrc);
      return result.get() ? object(InfoV1_Wrapper(result)) : object();
    }
    object get(PSEvt::Event& evt, Pds::Src& src, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<InfoV1> result = evt.get(src, key, foundSrc);
      return result.get() ? object(InfoV1_Wrapper(result)) : object();
    }
    object get(PSEvt::Event& evt, PSEvt::Source& source, const std::string& key=std::string(), Pds::Src* foundSrc=0) {
      shared_ptr<InfoV1> result = evt.get(source, key, foundSrc);
      return result.get() ? object(InfoV1_Wrapper(result)) : object();
    }
  };
} // namespace Princeton
} // namespace Psana
#endif // PSANA_PRINCETON_DDL_WRAPPER_H
