#!/bin/sh
#
# Shell script which runs a manages a bunch of controllers
#
# $Id$
#

# Number of translator instances to run, 0 = number of cores
translators=0

# release directory
release=/reg/g/psdm/sw/releases/0.2.22
#release=/reg/neh/home/salnikov/releases/ic-0.2.20

# database options
conn_file=/reg/g/psdm/psdatmgr/ic/.icdb-conn

# config section names to read from database
#config="meta-db group-time compress no-split xtc-lustre"
config="group-time compress no-split xtc-lustre l1-offset"

# log directory
logdir=/reg/g/psdm/psdatmgr/ic/log

# ===================================================================

usage () {
  echo "Usage: $(basename $0) [options]"
  echo "  Options:"
  echo "    -h        - print this message"
  echo "    -n number - number of translators, def: $translators"
  echo "    -r path   - release directory, def: $release"
  echo "    -p path   - PID file path, def: none"
}

while getopts hn:r:p: c ; do
  case $c in
    h) usage ; exit 0 ;;
    n) translators="$OPTARG" ;;
    r) release="$OPTARG" ;;
    p) pidfile="$OPTARG" ;;
    \?) usage ; exit 2 ;;
  esac
done
shift `expr $OPTIND - 1`

# count cores if translators=0
test $translators -eq 0 && translators=`gawk '/^processor[ \t]*:/{n=n+1} END {print n}' /proc/cpuinfo`

# allow world access
umask 022

# create log dir
test -d "$logdir" || mkdir -p "$logdir" || exit 2

# redirect output
time=`date +%Y%m%dT%H%M%S`
log="$logdir/ic-controller/ic-controller-$time-`hostname`.log"

echo "Running from release $release" >> "$log"
echo "Number of instances: $translators" >> "$log"
echo "Using configurations $config" >> "$log"

# have to be in release directory
cd "$release"

# run setup script, it should guess everything based on the current directory
. /reg/g/psdm/bin/lusi_setup.sh

# set config options
config_opt=""
for c in $config ; do
	config_opt="$config_opt -c $c"
done

ic-controller -d "file:${conn_file}" $config_opt -n $translators -l "$log" -v -v -v &
pid=$!

# store PID
test -n "$pidfile" && echo $pid >"$pidfile"

exit
