#--------------------------------------------------------------------------
# File and Version Information:
#  $Id: SConscript 4668 2012-11-01 18:13:44Z salnikov@SLAC.STANFORD.EDU $
#
# Description:
#  SConscript file for package tables
#------------------------------------------------------------------------

# Do not delete following line, it must be present in
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries,
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "mpi4py"
pkg_ver = "1.3.1c"

PREFIX  = pjoin('$SIT_EXTERNAL_SW', pkg, pkg_ver)
PYDIR = pjoin("lib", '$PYTHON', "site-packages")

PKGINFO = (pkg, pkg_ver, '$PYTHON', '$SIT_ARCH.found')

standardExternalPackage( pkg, **locals() )
