#!/bin/sh
usage() {
  echo Usage: `basename $0` file
}
if [ $# -eq 0 ] ; then
  usage
  exit 2
fi
irule "replToHPSS||delayExec(<PLUSET>3s</PLUSET>,msiDataObjReplWithOptions(*PATH,hpss-resc,all,*RES),nop)|nop" "*PATH=$1" "*RES"

