#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package pyextra
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "pyextra"

PREFIX = pjoin('$SIT_EXTERNAL_SW', pkg + "-$PYTHON")
BINDIR = "bin"
LINKBINS = "buildbot cython easy_install pylint sphinx-autogen sphinx-apidoc sphinx-build sphinx-quickstart virtualenv"
PYDIR = pjoin("lib", '$PYTHON', 'site-packages')
PYDIRSEP = True
PKGINFO = (pkg, '$PYTHON', '$SIT_ARCH.found')

standardExternalPackage(pkg, **locals())
