#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package matplotlib
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

mpl_ver = "0.99.1.2"
python_ver = env['PYTHON_VERSION']
PREFIX  = pjoin(env['SIT_ROOT'],"sw/external/matplotlib",mpl_ver)

PYDIR = "lib"
if env['SIT_ARCH_PROC'] == 'x86_64' : PYDIR = "lib64"
PYDIR += "/python"+python_ver+"/site-packages"

standardExternalPackage ( 'matplotlib', **locals() )
