#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package root
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

root_ver = "5.24.00"
PREFIX  = pjoin(env['SIT_ROOT'],"sw/external/root",root_ver)

INCDIR = "include/root"

LIBDIR = "lib"
LINKLIBS = "lib*.so*"
PKGLIBS = "Core Cint RIO Net Hist Graf Graf3d Gpad Tree Rint Postscript Matrix Physics MathCore Thread m dl"

BINDIR = "bin"
LINKBINS = "root root.exe rootcint"

PYDIR = "lib"
LINKPY = "*.py libPyROOT.so*"

standardExternalPackage ( 'root', **locals() )
