#!/usr/bin/env python 

import sys
import fcntl

"""
Try to aquire a raad lock on a file.

Usage:
  check_for_lock.py <fname>
"""



def main():

    fp = open(sys.argv[1])
    try:
        fcntl.lockf(fp, fcntl.LOCK_SH | fcntl.LOCK_NB)
    except IOError:
        print "Failed to obtain lock"
    else:
        print "Obtained lock"
    fcntl.lockf(fp, fcntl.LOCK_UN)
        
    fp.close()


if __name__ == "__main__":

    main()
