#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package pylsf
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "lsf_libs"
pkg_ver = "6.1"

PREFIX  = pjoin('$SIT_EXTERNAL_SW', 'lsf', pkg_ver)
LIBDIR = 'lib'
OPTIONAL = True
PKGINFO = None

standardExternalPackage ( pkg, **locals() )

del LIBDIR

pkg = "pylsf"
pkg_ver = "20110926"

PREFIX  = pjoin('$SIT_EXTERNAL_SW', pkg, pkg_ver)
PYDIR = pjoin('$PYTHON_LIBDIRNAME', '$PYTHON', "site-packages")
PKGINFO = (pkg, pkg_ver, '$PYTHON', '$SIT_ARCH.found')
DEPS = 'lsf_libs'
OPTIONAL = True

standardExternalPackage ( pkg, **locals() )
