#!/bin/sh
#
# $Id$

usage() {
  echo "Usage: $(basename $0) [options] output-dir package [...]"
  echo
  echo "Availabale options:"
  echo "    -h        print this message"
  echo "    -d        debug (turn on -x shell option)"
  echo "    -p name   set project name"
}

# default values for options
project=""

# get the options
while getopts hdm:p: c ; do
  case $c in
    h) usage ; exit 0 ;;
    d) set -x ;;
    p) project="$OPTARG" ;;
    \?) usage ; exit 2 ;;
  esac
done
shift `expr $OPTIND - 1`

# get output directory name and file/package list
if [ $# -lt 2 ] ; then
  usage
  exit 2
fi
output="$1"
shift
packages="$@"

# filter non-existing packages/files
allpackages="$packages"
packages=
for pkg in $allpackages; do
  if [ -e $pkg ] ; then
    packages="$packages $pkg"
  else
    echo "Package or file $pkg does not exist, skipping."
  fi
done

# try to make directory
mkdir -p "$output" 2>/dev/null

# run doxygen
doxygen - << EOD 
PROJECT_NAME           = $project
OUTPUT_DIRECTORY       = $output
CREATE_SUBDIRS         = NO
BUILTIN_STL_SUPPORT    = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = NO
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES
INPUT                  = $packages
FILE_PATTERNS          = *.h *.py *.cpp *.dox
RECURSIVE              = YES
SOURCE_BROWSER         = YES
STRIP_CODE_COMMENTS    = NO
GENERATE_HTML          = YES
GENERATE_LATEX         = NO
GENERATE_MAN           = NO
EOD
