//--------------------------------------------------------------------------
// File and Version Information:
// 	$Id$
//
// Description:
//	Class RootH1...
//
// Author List:
//      Mikhail S. Dubrovin
//
//------------------------------------------------------------------------

//-----------------------
// This Class's Header --
//-----------------------
#include "RootHist/RootH1.h"
#include "PSHist/HManager.h" // to get type_int, type_float, etc.  

//-----------------
// C/C++ Headers --
//-----------------
#include <sstream> // for int to string conversion using std::stringstream 
#include <iomanip> // for formatted conversion std::setw(3) , std::setfill

using std::cout;
using std::endl;
using std::ostream;

//-------------------------------
// Collaborating Class Headers --
//-------------------------------

//-----------------------------------------------------------------------
// Local Macros, Typedefs, Structures, Unions and Forward Declarations --
//-----------------------------------------------------------------------

//		----------------------------------------
// 		-- Public Function Member Definitions --
//		----------------------------------------

namespace RootHist {

int RootH1::s_number_of_booked_histograms = 0;

//----------------
// Constructors --
//----------------
RootH1::RootH1 ( int type, const std::string &name, const std::string &title, int nbins, double xlow, double xhigh )
  : PSHist::H1()
{
  cout << "Create histogram with type=" << type << endl;
  //printHistogramDataTypes();

  m_hnumber = ++s_number_of_booked_histograms;
  m_type    = type;

  switch ( m_type )
    {
      case PSHist::HManager::type_double : { m_hist1d = new TH1D( name.c_str(), title.c_str(), nbins, xlow, xhigh ); }
      case PSHist::HManager::type_float  : { m_hist1f = new TH1F( name.c_str(), title.c_str(), nbins, xlow, xhigh ); }
      case PSHist::HManager::type_int    : { m_hist1i = new TH1I( name.c_str(), title.c_str(), nbins, xlow, xhigh ); }
      default : { }
    }
}

//--------------
// Destructor --
//--------------
RootH1::~RootH1 ()
{
}


// factory for 1d histograms
template <typename HTYPE>
HTYPE* makeH1(const std::string& name, const std::string& title, int nbins, double xlow, double xhigh )
{
    return new HTYPE(name.c_str(), title.c_str(), nbins, xlow, xhigh);
}  


void RootH1::print(ostream &o) const
{ 
  o << "RootH1, title" << endl;
}


void RootH1::fill( double x, double weight ) {

  switch ( m_type )
    {
      case PSHist::HManager::type_double : { m_hist1d->Fill( x, weight ); }
      case PSHist::HManager::type_float  : { m_hist1f->Fill( x, weight ); }
      case PSHist::HManager::type_int    : { m_hist1i->Fill( x, weight ); }
      default : { }
    }

  /*
  if ( histp->IsA() == TProfile::Class() ) {
    ((TProfile*)histp)->Fill( x , weight , 1. );
  }
  else if ( histp->IsA() == TH2F::Class() ) {
    ((TH2F*)histp)->Fill( x, weight , 1. );
  }
  else {
    histp->Fill( x, weight );
  }
  return;
  */
} 


void RootH1::reset() {
  switch ( m_type )
    {
      case PSHist::HManager::type_double : { m_hist1d->Reset(); }
      case PSHist::HManager::type_float  : { m_hist1f->Reset(); }
      case PSHist::HManager::type_int    : { m_hist1i->Reset(); }
      default : { }
    }
  //m_hist->Reset();
}


// RootH1::getAutoGeneratedName() generates an automatic name for histogram, which looks like: H1_N0001
std::string RootH1::getAutoGeneratedName() {
  std::stringstream stream_hname;
  stream_hname << "H1_N" << std::setw(4) << std::setfill('0') << m_hnumber;
  m_hname = stream_hname.str();
  return m_hname;
}


void RootH1::printHistogramDataTypes()
{
  cout << "type_double=" << PSHist::HManager::type_double << endl;
  cout << "type_float =" << PSHist::HManager::type_float  << endl;
  cout << "type_int   =" << PSHist::HManager::type_int    << endl;
}

} // namespace RootHist


