#!/bin/sh

srcdir="/psdm/local/releases"
dstdir="/afs/slac.stanford.edu/g/lusi/sw/releases"
reqdir="$srcdir/copy-requests"

#
# Check that request directory exists
#
if [ ! -d "$reqdir" ] ; then
    echo "$0: cannot find request directory $reqdir"
    exit 2
fi

#
# See if there are any requests, take first
#
rel=`/bin/ls -1 "$reqdir" | sort | head -1`
test -z "$rel" && exit 0

#
# remove request
#
rm "$reqdir/$rel" || exit 2

#
# redirect output to logfile
#
logdir="$dstdir/logs/$rel"
if [ ! -d "$logdir" ] ; then 
    if mkdir "$logdir" ; then
        :
    else
        echo "Failed to create log directory: $logdir/$rel" 1>&2
        exit 2
    fi
fi
exec > "$logdir/copy-nightly" 2>&1

echo "+++ Will copy new release $rel"
echo "+++ Checking directories"

#
# Check that the source directory exists
#
if [ ! -d "$srcdir/$rel" ] ; then
    echo "Release does not exist: $srcdir/$rel" 1>&2
    exit 2
fi

#
# Check that the destination directory does not exists
#
if [ -d "$dstdir/$rel" ] ; then
    echo "Destination release already exists: $dstdir/$rel" 1>&2
    exit 2
fi

#
# Check that we can make a directory for destination
#
if mkdir "$dstdir/$rel" ; then
    :
else
    echo "Failed to create release directory: $dstdir/$rel" 1>&2
    exit 2
fi

#
# do the copy
#
echo "+++ Start copying the release"
gtar -C "$srcdir" -c -f - "$rel" | gtar -C "$dstdir" -x -v -f - "$rel"

echo "+++ Done"
