#!/bin/sh

reldir="/psdm/local/releases"

rel=${1:?Required parameter missing (release name)}
tags=${2:?Required parameter missing (tags name)}

#
# Standard LUSI setup
#
. /afs/slac.stanford.edu/g/lusi/bin/lusi_setup.sh
tmp=${LUSI_ROOT:?Missing LUSI_ROOT}

checkout() {

    #
    # directory for the new release
    #
    if [ -d "$reldir/$rel" ] ; then
        echo "Directory $reldir/$rel already exists" 1>&2
        return 2
    fi
    cd "$reldir" || return 3
    newrel "$rel" "$rel" || return 3
    cd "$rel"

    #
    # get the list of the tags
    #
    cp "$LUSI_ROOT/sw/releases/buildbot/tags/$tags" ./tags || return 3

    #
    # checkout all packages from the tag list
    #
    addpkg -x -f ./tags || return 3
}


#
# execute it, get its output in the logs
#
log=/tmp/cron-rel-co-$$
checkout > $log.out 2> $log.err
    
#
# copy the logs to the release, these will be used by the next stage
# as a sign that we are done
#
test -s $log.err && cp $log.err "$reldir/$rel/.co-done.err"
rm $log.err
mv $log.out "$reldir/$rel/.co-done.out"
mv "$reldir/$rel/.co-done.out" "$reldir/$rel/.co-done"
