#!/bin/sh

set -e

if [ ! -d psddldata/data/ ]; then
    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
    exit 1
fi

files=`ls -1 psddldata/data/*.ddl | grep -v xtc.ddl`

echo "" > psddl_python/src/WrapperList.txt
for f in $files ; do
  module=`basename $f .ddl`
  package=`gawk '/^ *@package/{print $2}' $f`
  echo "DECL($package)" >> psddl_python/src/WrapperList.txt
  echo "module $module, package $package"
  psddlc -b python -I data -I psddl_psana -t psddl_python -B dev-types=$devtypes \
    -e psddl_python/include/$module.ddl.h \
    -o psddl_python/src/$module.ddl.cpp \
    psddldata/data/$module.ddl
done
