#!/bin/sh
#
# Shell script which runs a manages a bunch of controllers
#
# $Id$
#

# release directory
release=dm-current

# log directory
logdir=/reg/g/psdm/psdatmgr/ic/log

no_ffb="-O AMO -O CXI -O MEC -O MOB -O SXR"

prog=ic-auto-translate

# ===================================================================

usage () {
    echo "Usage: $(basename $0) [options]"
    echo "  Options:"
    echo "    -h        - print this message"
    echo "    -r path   - release directory, def: $release"
    echo "    -p path   - PID file path, def: none"
}

while getopts hr:p: c ; do
    case $c in
        h) usage ; exit 0 ;;
        r) release="$OPTARG" ;;
        p) pidfile="$OPTARG" ;;
        \?) usage ; exit 2 ;;
    esac
done
shift `expr $OPTIND - 1`

# allow world access
umask 022

# create log dir
test -d "${logdir}" || mkdir -p "${logdir}" || exit 2

# redirect output
time=$(date +%Y%m%dT%H%M%S)
log="${logdir}/ic-controller/ic-auto-translate-${time}-$(hostname).log"
exec >"${log}" 2>&1

# run setup script, it should guess everything based on the current directory
. /reg/g/psdm/bin/sit_setup.sh "${release}"

echo "Running from release ${release}"
type ${prog} 


PYTHONUNBUFFERED=x ${cmd} -v -v ${no_ffb} &
pid=$!
[[ -n "${pidfile}" ]] && echo ${pid} > "${pidfile}"

exit
