#!/bin/bash
#
# Shell script which runs a manages a bunch of controllers
#
# $Id: ic-controller-runner 6167 2013-04-26 00:59:00Z salnikov@SLAC.STANFORD.EDU $
#

# release directory the controller runs from
release=/reg/g/psdm/sw/releases/dm-current

# database options
conn_file=/reg/g/psdm/psdatmgr/ic/.icdb-conn

# config section names to read from database
config="compress no-split xtc-lustre calib-data pazlib live-mode fm-irods"

# log directory
logdir=/reg/g/psdm/psdatmgr/ic/log

# ===================================================================

usage () {
    echo "Usage: $(basename $0) [options]"
    echo "  Options:"
    echo "    -h        - print this message"
    echo "    -p path   - PID file path, def: none"
    echo "    -r path   - release directory, def: $release"
}

while getopts hp:r: c ; do
    case $c in
        h) usage ; exit 0 ;;
        p) pidfile="$OPTARG" ;;
        r) release="$OPTARG" ;;
        \?) usage ; exit 2 ;;
    esac
done
shift `expr $OPTIND - 1`

# allow world access
umask 022

# create log dir
test -d "${logdir}" || mkdir -p "${logdir}" || exit 2

# redirect output
time=$(date +%Y%m%dT%H%M%S)
log="${logdir}/ic-controller/ic-controller-${time}-$(hostname).log"

test -h "${release}" && sym=" -> $(readlink ${release})"
echo "Running from release ${release}${sym}" >> "${log}"
echo "Using configurations ${config}" >> "${log}"

# have to be in release directory
cd "${release}"

# run setup script, it should guess everything based on the current directory
. /reg/g/psdm/bin/sit_setup.sh

# set config options
config_opt=""
for c in $config ; do
    config_opt="${config_opt} -c ${c}"
done

ic-controller-psana -d "file:${conn_file}" ${config_opt} -l "${log}" -v -v &
pid=$!

# store PID
test -n "${pidfile}" && echo ${pid} > "${pidfile}"

exit
