#!/bin/bash	
#
#  Start the queue that submits requests to create missing index files.
#

. /reg/g/psdm/bin/sit_setup.sh dm-current

which idx_failed_regdb
echo "Start idx_failed_regdb $@" 

exec idx_failed_regdb "$@"
