#!/bin/bash	
#
#  Start the queue that submits requests to create missing index files.
#

. /reg/g/psdm/bin/sit_setup.sh dm-current

which idx-failed-regdb
echo "Start idx-failed-regdb $@" 

exec idx-failed-regdb "$@"
