#!/bin/bash


IRODS_HOME=/reg/g/psdm/psdatmgr/irods/iRODS-server
KRB5_KTNAME=$IRODS_HOME/server/config/irods.keytab
PORTS="svrPortRangeStart=40000 svrPortRangeEnd=41000"

. /etc/init.d/functions
RETVAL=0

Env="HOME=/reg/neh/home1/psdatmgr"

test -f "$KRB5_KTNAME" && Env="$Env KRB5_KTNAME=$KRB5_KTNAME"

# start irods 
$Env $PORTS $IRODS_HOME/irodsctl start
