#!/bin/bash 

superd=/reg/neh/home1/psdatmgr/dm_venv/supervisor/bin/supervisord
cfg=/reg/g/psdm/etc/supervisord_$(hostname -s).conf

[[ ! -e $cfg ]] && echo "No config $cfg" && exit 1

. /reg/g/psdm/bin/sit_setup.sh dm-current

${superd} -c ${cfg}





