#ifndef APPUTILS_APPCMDEXCEPTIONS_H
#define APPUTILS_APPCMDEXCEPTIONS_H

//--------------------------------------------------------------------------
// File and Version Information:
// 	$Id$
//
// Description:
//	Class AppCmdExceptions.
//
//------------------------------------------------------------------------

//-----------------
// C/C++ Headers --
//-----------------
#include <stdexcept>

//----------------------
// Base Class Headers --
//----------------------

//-------------------------------
// Collaborating Class Headers --
//-------------------------------

//------------------------------------
// Collaborating Class Declarations --
//------------------------------------

//		---------------------
// 		-- Class Interface --
//		---------------------

namespace AppUtils {

/// @addtogroup AppUtils_Exceptions

/**
 *  @ingroup AppUtils_Exceptions
 *
 *  @brief Base class for all exceptions generated by AppUtils package
 *
 *  This software was developed for the LCLS project.  If you use all or
 *  part of it, please give an appropriate acknowledgement.
 *
 *  @version $Id$
 *
 *  @author Andrei Salnikov
 */
class AppCmdException : public std::runtime_error {
public:
  AppCmdException ( const std::string& msg ) ;
};

/// Exception thrown when conversion from string to other type fails
class AppCmdTypeCvtException : public AppCmdException {
public:
  AppCmdTypeCvtException ( const std::string& string, const std::string& type ) ;
};

/// Exception thrown when conversion from string to other type via lexical_cast fails
class AppCmdLexicalCastFromStringException : public AppCmdException {
public:
  AppCmdLexicalCastFromStringException ( const std::string& string, const std::string& message ) ;
};

/// Exception thrown when conversion from value to string via lexical_cast fails
class AppCmdLexicalCastToStringException : public AppCmdException {
public:
  AppCmdLexicalCastToStringException ( const std::string& message ) ;
};

/// Exception thrown when conversion from string to other type via lexical_cast fails
class AppCmdTypeLexicalCastException : public AppCmdException {
public:
  AppCmdTypeLexicalCastException ( const std::string& string, const std::string& message ) ;
};

/// Exception thrown when option with the same name was already defined
class AppCmdOptDefinedException : public AppCmdException {
public:
  AppCmdOptDefinedException ( const std::string& option ) ;
};

/// Exception thrown when option name is not known
class AppCmdOptUnknownException : public AppCmdException {
public:
  AppCmdOptUnknownException ( const std::string& option ) ;
};

/// Exception thrown when argument order is messed up (required after optional)
class AppCmdArgOrderException : public AppCmdException {
public:
  AppCmdArgOrderException ( const std::string& arg ) ;
};

/// Exception thrown when option name contains invalid characters
class AppCmdOptNameException : public AppCmdException {
public:
  AppCmdOptNameException ( const std::string& option ) ;
};

/// Exception thrown when positional argument list is too long
class AppCmdArgListTooLong : public AppCmdException {
public:
  AppCmdArgListTooLong();
};

/// Exception thrown when positional argument list is too long
class AppCmdArgListTooShort : public AppCmdException {
public:
  AppCmdArgListTooShort();
};

} // namespace AppUtils

#endif // APPUTILS_APPCMDEXCEPTIONS_H
