#------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package pyfits
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage


pkg = "pyfits"
pkg_ver = "2.3.1"

PREFIX = pjoin('$SIT_EXTERNAL_SW', pkg, pkg_ver)
PYDIR = pjoin('$LIB_ABI', '$PYTHON', "site-packages")
PKGINFO = (pkg, pkg_ver, '$PYTHON', '$SIT_ARCH.found')

standardExternalPackage(pkg, **locals())
