/* Do not edit this file, as it is auto-generated */

#ifndef PSDDL_PYTHON_EPICS_DDL_WRAPPER_H
#define PSDDL_PYTHON_EPICS_DDL_WRAPPER_H 1

#include <vector>
#include "psddl_python/DdlWrapper.h"
#include "psddl_python/Converter.h"
#include "ndarray/ndarray.h"
#include "pdsdata/xtc/TypeId.hh"
#include "psddl_psana/epics.ddl.h" // inc_psana

namespace psddl_python {
namespace Epics {

using namespace boost::python;
using boost::python::api::object;
using boost::shared_ptr;
using std::vector;

void createWrappers(PyObject* module);

class EpicsPvHeader_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvHeader> m_obj;
public:
  EpicsPvHeader_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvHeader>& obj) : m_obj(obj) {}
  int16_t pvId() const { return m_obj->pvId(); }
  int16_t dbrType() const { return m_obj->dbrType(); }
  int16_t numElements() const { return m_obj->numElements(); }
  void print() const { m_obj->print(); }
  uint8_t isCtrl() const { return m_obj->isCtrl(); }
  uint8_t isTime() const { return m_obj->isTime(); }
  uint16_t status() const { return m_obj->status(); }
  uint16_t severity() const { return m_obj->severity(); }
};

class EpicsPvCtrlHeader_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlHeader> m_obj;
public:
  EpicsPvCtrlHeader_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlHeader>& obj) : m_obj(obj) {}
  const char* pvName() const { return m_obj->pvName(); }
  boost::python::list pvName_shape() const { boost::python::list res; const vector<int>& sh=m_obj->pvName_shape(); for (vector<int>::const_iterator i = sh.begin(); i != sh.end(); ++ i) res.append(*i); return res; }
};

class EpicsPvTimeHeader_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeHeader> m_obj;
public:
  EpicsPvTimeHeader_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeHeader>& obj) : m_obj(obj) {}
  Psana::Epics::epicsTimeStamp stamp() const { return m_obj->stamp(); }
};

class EpicsPvCtrlString_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlString> m_obj;
public:
  EpicsPvCtrlString_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlString>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_sts_string& dbr() const { return m_obj->dbr(); }
  const char* data(uint32_t i0) const { return m_obj->data(i0); }
  const char* value(uint32_t i) const { return m_obj->value(i); }
  boost::python::list data_shape() const { boost::python::list res; const vector<int>& sh=m_obj->data_shape(); for (vector<int>::const_iterator i = sh.begin(); i != sh.end(); ++ i) res.append(*i); return res; }
  boost::python::list data_list() { boost::python::list l; const int n = m_obj->data_shape()[0]; for (int i = 0; i < n; i++) l.append(data(i)); return l; }
};

class EpicsPvCtrlShort_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlShort> m_obj;
public:
  EpicsPvCtrlShort_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlShort>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_short& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  int16_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvCtrlFloat_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlFloat> m_obj;
public:
  EpicsPvCtrlFloat_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlFloat>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_float& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  float value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvCtrlEnum_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlEnum> m_obj;
public:
  EpicsPvCtrlEnum_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlEnum>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_enum& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  uint16_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvCtrlChar_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlChar> m_obj;
public:
  EpicsPvCtrlChar_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlChar>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_char& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  uint8_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvCtrlLong_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlLong> m_obj;
public:
  EpicsPvCtrlLong_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlLong>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_long& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  int32_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvCtrlDouble_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvCtrlDouble> m_obj;
public:
  EpicsPvCtrlDouble_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvCtrlDouble>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_ctrl_double& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  double value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeString_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeString> m_obj;
public:
  EpicsPvTimeString_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeString>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_string& dbr() const { return m_obj->dbr(); }
  const char* data(uint32_t i0) const { return m_obj->data(i0); }
  const char* value(uint32_t i) const { return m_obj->value(i); }
  boost::python::list data_shape() const { boost::python::list res; const vector<int>& sh=m_obj->data_shape(); for (vector<int>::const_iterator i = sh.begin(); i != sh.end(); ++ i) res.append(*i); return res; }
  boost::python::list data_list() { boost::python::list l; const int n = m_obj->data_shape()[0]; for (int i = 0; i < n; i++) l.append(data(i)); return l; }
};

class EpicsPvTimeShort_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeShort> m_obj;
public:
  EpicsPvTimeShort_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeShort>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_short& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  int16_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeFloat_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeFloat> m_obj;
public:
  EpicsPvTimeFloat_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeFloat>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_float& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  float value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeEnum_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeEnum> m_obj;
public:
  EpicsPvTimeEnum_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeEnum>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_enum& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  uint16_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeChar_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeChar> m_obj;
public:
  EpicsPvTimeChar_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeChar>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_char& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  uint8_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeLong_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeLong> m_obj;
public:
  EpicsPvTimeLong_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeLong>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_long& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  int32_t value(uint32_t i) const { return m_obj->value(i); }
};

class EpicsPvTimeDouble_Wrapper {
  shared_ptr<const Psana::Epics::EpicsPvTimeDouble> m_obj;
public:
  EpicsPvTimeDouble_Wrapper(const shared_ptr<const Psana::Epics::EpicsPvTimeDouble>& obj) : m_obj(obj) {}
  const Psana::Epics::dbr_time_double& dbr() const { return m_obj->dbr(); }
  PyObject* data() const { return detail::ndToNumpy(m_obj->data(), m_obj); }
  double value(uint32_t i) const { return m_obj->value(i); }
};

class PvConfigV1_Wrapper {
  shared_ptr<const Psana::Epics::PvConfigV1> m_obj;
public:
  PvConfigV1_Wrapper(const shared_ptr<const Psana::Epics::PvConfigV1>& obj) : m_obj(obj) {}
  int16_t pvId() const { return m_obj->pvId(); }
  const char* description() const { return m_obj->description(); }
  float interval() const { return m_obj->interval(); }
};

class ConfigV1_Wrapper {
  shared_ptr<const Psana::Epics::ConfigV1> m_obj;
public:
  enum { TypeId = Pds::TypeId::Id_EpicsConfig };
  enum { Version = 1 };
  ConfigV1_Wrapper(const shared_ptr<const Psana::Epics::ConfigV1>& obj) : m_obj(obj) {}
  int32_t numPv() const { return m_obj->numPv(); }
  Epics::PvConfigV1_Wrapper pvControls(uint32_t i0) const { return Epics::PvConfigV1_Wrapper(boost::shared_ptr<const Psana::Epics::PvConfigV1>(m_obj, &m_obj->pvControls(i0))); }
  boost::python::list pvControls_shape() const { boost::python::list res; const vector<int>& sh=m_obj->pvControls_shape(); for (vector<int>::const_iterator i = sh.begin(); i != sh.end(); ++ i) res.append(*i); return res; }
  boost::python::list pvControls_list() { boost::python::list l; const int n = m_obj->pvControls_shape()[0]; for (int i = 0; i < n; i++) l.append(pvControls(i)); return l; }
};

  class epicsTimeStamp_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::epicsTimeStamp);}
    const char* getTypeName() const { return "Psana::Epics::epicsTimeStamp";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::epicsTimeStamp> result = boost::static_pointer_cast<Psana::Epics::epicsTimeStamp>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_string_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_string);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_string";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_string> result = boost::static_pointer_cast<Psana::Epics::dbr_time_string>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_short_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_short);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_short";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_short> result = boost::static_pointer_cast<Psana::Epics::dbr_time_short>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_float_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_float);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_float";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_float> result = boost::static_pointer_cast<Psana::Epics::dbr_time_float>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_enum_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_enum);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_enum";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_enum> result = boost::static_pointer_cast<Psana::Epics::dbr_time_enum>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_char_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_char);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_char";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_char> result = boost::static_pointer_cast<Psana::Epics::dbr_time_char>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_long_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_long);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_long";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_long> result = boost::static_pointer_cast<Psana::Epics::dbr_time_long>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_time_double_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_time_double);}
    const char* getTypeName() const { return "Psana::Epics::dbr_time_double";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_time_double> result = boost::static_pointer_cast<Psana::Epics::dbr_time_double>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_sts_string_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_sts_string);}
    const char* getTypeName() const { return "Psana::Epics::dbr_sts_string";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_sts_string> result = boost::static_pointer_cast<Psana::Epics::dbr_sts_string>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_short_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_short);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_short";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_short> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_short>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_float_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_float);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_float";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_float> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_float>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_enum_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_enum);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_enum";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_enum> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_enum>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_char_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_char);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_char";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_char> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_char>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_long_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_long);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_long";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_long> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_long>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class dbr_ctrl_double_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::dbr_ctrl_double);}
    const char* getTypeName() const { return "Psana::Epics::dbr_ctrl_double";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::dbr_ctrl_double> result = boost::static_pointer_cast<Psana::Epics::dbr_ctrl_double>(vdata);
      return result.get() ? object(*result) : object();
    }
  };

  class EpicsPvHeader_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvHeader);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvHeader";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvHeader> result = boost::static_pointer_cast<Psana::Epics::EpicsPvHeader>(vdata);
      return result.get() ? object(EpicsPvHeader_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlHeader_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlHeader);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlHeader";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlHeader> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlHeader>(vdata);
      return result.get() ? object(EpicsPvCtrlHeader_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeHeader_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeHeader);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeHeader";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeHeader> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeHeader>(vdata);
      return result.get() ? object(EpicsPvTimeHeader_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlString_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlString);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlString";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlString> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlString>(vdata);
      return result.get() ? object(EpicsPvCtrlString_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlShort_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlShort);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlShort";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlShort> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlShort>(vdata);
      return result.get() ? object(EpicsPvCtrlShort_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlFloat_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlFloat);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlFloat";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlFloat> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlFloat>(vdata);
      return result.get() ? object(EpicsPvCtrlFloat_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlEnum_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlEnum);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlEnum";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlEnum> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlEnum>(vdata);
      return result.get() ? object(EpicsPvCtrlEnum_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlChar_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlChar);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlChar";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlChar> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlChar>(vdata);
      return result.get() ? object(EpicsPvCtrlChar_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlLong_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlLong);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlLong";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlLong> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlLong>(vdata);
      return result.get() ? object(EpicsPvCtrlLong_Wrapper(result)) : object();
    }
  };

  class EpicsPvCtrlDouble_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvCtrlDouble);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvCtrlDouble";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvCtrlDouble> result = boost::static_pointer_cast<Psana::Epics::EpicsPvCtrlDouble>(vdata);
      return result.get() ? object(EpicsPvCtrlDouble_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeString_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeString);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeString";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeString> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeString>(vdata);
      return result.get() ? object(EpicsPvTimeString_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeShort_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeShort);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeShort";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeShort> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeShort>(vdata);
      return result.get() ? object(EpicsPvTimeShort_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeFloat_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeFloat);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeFloat";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeFloat> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeFloat>(vdata);
      return result.get() ? object(EpicsPvTimeFloat_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeEnum_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeEnum);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeEnum";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeEnum> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeEnum>(vdata);
      return result.get() ? object(EpicsPvTimeEnum_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeChar_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeChar);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeChar";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeChar> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeChar>(vdata);
      return result.get() ? object(EpicsPvTimeChar_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeLong_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeLong);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeLong";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeLong> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeLong>(vdata);
      return result.get() ? object(EpicsPvTimeLong_Wrapper(result)) : object();
    }
  };

  class EpicsPvTimeDouble_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::EpicsPvTimeDouble);}
    const char* getTypeName() const { return "Psana::Epics::EpicsPvTimeDouble";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::EpicsPvTimeDouble> result = boost::static_pointer_cast<Psana::Epics::EpicsPvTimeDouble>(vdata);
      return result.get() ? object(EpicsPvTimeDouble_Wrapper(result)) : object();
    }
  };

  class PvConfigV1_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::PvConfigV1);}
    const char* getTypeName() const { return "Psana::Epics::PvConfigV1";}
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::PvConfigV1> result = boost::static_pointer_cast<Psana::Epics::PvConfigV1>(vdata);
      return result.get() ? object(PvConfigV1_Wrapper(result)) : object();
    }
  };

  class ConfigV1_Converter : public psddl_python::Converter {
  public:
    const std::type_info* typeinfo() const { return &typeid(Psana::Epics::ConfigV1);}
    const char* getTypeName() const { return "Psana::Epics::ConfigV1";}
    int getVersion() const { return Psana::Epics::ConfigV1::Version; }
    int pdsTypeId() const { return Pds::TypeId::Id_EpicsConfig; }
    object convert(const boost::shared_ptr<void>& vdata) const {
      shared_ptr<Psana::Epics::ConfigV1> result = boost::static_pointer_cast<Psana::Epics::ConfigV1>(vdata);
      return result.get() ? object(ConfigV1_Wrapper(result)) : object();
    }
  };
} // namespace Epics
} // namespace psddl_python
#endif // PSDDL_PYTHON_EPICS_DDL_WRAPPER_H
