#!/bin/sh

echo "" > psana_python/src/WrapperList.txt
for f in  psddldata/data/*.ddl.xml ; do
  module=`basename $f .ddl.xml`
  if [ "$module" == "xtc" ] ; then
      continue
  fi
  package=`grep "package name" $f | sed -e 's,^.*name=",,' -e 's,".*,,'`
  echo "DECL($package)" >> psana_python/src/WrapperList.txt
  echo "module $module, package $package"
  psddlc -b python -I data -I psddl_psana --t Psana -e psddl_python/include/$module.ddl.wrapper.h -o psddl_python/src/$module.ddl.wrapper.cpp psddldata/data/$module.ddl.xml
done
