#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package h5py
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "h5py"
pkg_ver = "1.3.0-vlen-1.8.4p1"
PREFIX  = pjoin(env['SIT_ROOT'],"sw/external/h5py",pkg_ver)

PYDIR = "lib"
if env['SIT_ARCH_PROC'] == 'x86_64' : PYDIR = "lib64"
PYDIR += "/python"+env['PYTHON_VERSION']+"/site-packages"

standardExternalPackage ( pkg, **locals() )

