SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `SHIFTMGR` ;
USE `SHIFTMGR`;

-- -----------------------------------------------------
-- Table `SHIFTMGR`.`SHIFT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SHIFTMGR`.`SHIFT` ;

CREATE  TABLE IF NOT EXISTS `SHIFTMGR`.`SHIFT` (

  `id` INT NOT NULL AUTO_INCREMENT ,

  `instrument` VARCHAR(32) NOT NULL,

  `begin_time` INT NOT NULL,
  `end_time`   INT     DEFAULT NULL,


  PRIMARY KEY (`id`))

ENGINE = InnoDB ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
