SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `LOGS` ;
USE `LOGS`;

-- -----------------------------------------------------
-- Table `LOGS`.`GROUP_MANAGEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOGS`.`GROUP_MANAGEMENT` ;

CREATE  TABLE IF NOT EXISTS `LOGS`.`GROUP_MANAGEMENT` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `event_time` BIGINT UNSIGNED NOT NULL ,
  `requestor` VARCHAR(32) NOT NULL ,
  `requestor_host` VARCHAR(255) NOT NULL ,
  `operation` ENUM('ADD','DELETE') NOT NULL ,
  `user_account` VARCHAR(32) NOT NULL ,
  `group_name` VARCHAR(32) NOT NULL ,
  `group_type` ENUM('POSIX','NETGROUP') NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `GROUP_MANAGEMENT_EVENT_TIME` (`event_time` ASC)
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
