
// *** Do not edit this file, it is auto-generated ***

#include "psddl_psana/princeton.ddl.h"

#include <cstddef>

namespace Psana {
namespace Princeton {

ConfigV1::~ConfigV1() {}


ConfigV2::~ConfigV2() {}


FrameV1::~FrameV1() {}

} // namespace Princeton
} // namespace Psana
