#!/bin/bash 
#
# cron to gather the space usage of the ana file systems and add them
# to the fs_mon_stat table in the sysmon database. 
#
# Needs to run from a machine that has access to all ana file systems.
#


do_mail() {   
    mail -s "ANAFS stat failed $(date +'%Y%m%d %H:%M')" ${TO_ADDR} <<EOF

Cron job anafs-space-usage-cron failed on $(hostname)
recording date: $1

EOF
}


check_error()  {
    # Usage: check_error <time[s]>
    # check for row count. Expect line "ROWCOUNT 1"
    error=0
    while read line ; do
        case ${line} in
            ROWCOUNT*)
                n=( ${line} )
                [[ "${n[1]}" != '1' ]] && error=1
        esac
    done
    
    [[ ${error} -eq 1 ]] && do_mail $1
}


TO_ADDR="wilko"

# data base connection
connfn=/reg/g/psdm/psdatmgr/etc/.sysmon-conn

declare -A conn
for tok in $(head -1 ${connfn} | tr ';' ' ') ; do
    key=$( echo ${tok%%=*} | tr [:upper:] [:lower:])
    val=${tok#*=}
    conn[${key}]=${val}
done

for key in server database uid pwd ; do
    [[ -z ${conn[${key}]} ]] && echo "Missing key ${key}" && exit 1
done
conn_str="-h ${conn[server]} -u ${conn[uid]} --password=${conn[pwd]} ${conn[database]}"

disks=( /reg/data/ana01/ /reg/data/ana03/  /reg/data/ana04/ 
    /reg/data/ana11/  /reg/data/ana12/  /reg/data/ana14/ )

treg=$(date +%s)

for d in ${disks[@]} ; do
    res=($(df -t lustre -kP $d | grep -v "Filesystem"))
    used=${res[2]}
    avail=${res[3]}
    fs=$(basename $d)
    
    if [[ -z "${used}" ]] || [[ -z "${avail}" ]] ; then
        echo "File System error" 1>&2
        continue
    fi
    if [[ $(( ${used:-0} + ${avail:-0} )) -le 1 ]] ; then
	echo "Wrong sizes" 1>&2
	continue
    fi
    
    echo "insert into fs_mon_stat SELECT id,${treg},${used},${avail} FROM fs_mon_def WHERE fs_mon_def.group = 'ana' and fs_mon_def.name = '${fs}';"
    echo "select 'ROWCOUNT', ROW_COUNT();"
done | mysql --disable-column-names ${conn_str} | check_error ${treg} 

