#!/bin/bash 
#
# Cleanup data dirs on ioc recorder node
#
# Usage:  do_ioc_cleanup <user> <root-dir>
# 


. /reg/g/psdm/bin/sit_setup.sh /reg/neh/home1/wilko/release_dev/data_mover

export RUNUSER="/sbin/runuser $1 -s /bin/bash --preserve-environment -c"
# cleanup tm[ folder 
$RUNUSER "cd $2/../tmp; find . -type f -mtime +3 -exec rm -vf '{}' ';'"

# cleanup daq xtc files
$RUNUSER "iocxtccleanup --clean $2"

