#--------------------------------------------------------------------------
# File and Version Information:
#  $Id: SConscript 806 2010-03-26 17:32:36Z salnikov $
#
# Description:
#  SConscript file for package scipy
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

# it also needs ATLAS numeric stuff (shared libs only)
atlas_ver = "3.8.3"
PREFIX = pjoin('$SIT_EXTERNAL_SW', "atlas", atlas_ver)
LIBDIR = 'lib'
LINKLIBS = "*.so"
standardExternalPackage('atlas', **locals())


del LIBDIR
del LINKLIBS

scipy_ver = "0.7.1"
PREFIX = pjoin('$SIT_EXTERNAL_SW', "scipy", scipy_ver)

PYDIR = pjoin('$PYTHON_LIBDIRNAME', '$PYTHON', "site-packages", "scipy")
PYDIRSEP = True
PKGINFO = ("scipy", scipy_ver, '$PYTHON', '$SIT_ARCH.found')

standardExternalPackage('scipy', **locals())
