#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package unixodbc
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any LUSI project
Import('*')

import os
from os.path import join as pjoin

from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

unixodbc_ver = "2.2.12"

PREFIX  = pjoin(env['LUSI_ROOT'],"sw/external/unixODBC",unixodbc_ver,env['LUSI_ARCH'])
INCDIR  = "include"
LIBDIR  = "lib"
BINDIR  = "bin"
PKGLIBS = "odbc"
standardExternalPackage ( 'unixodbc', **locals() )
