
// *** Do not edit this file, it is auto-generated ***

#include <cstddef>
#include "psddl_psana/pulnix.ddl.h"
namespace Psana {
namespace Pulnix {

TM6740ConfigV1::~TM6740ConfigV1() {}


TM6740ConfigV2::~TM6740ConfigV2() {}

} // namespace Pulnix
} // namespace Psana
