#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package tables
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "pyqt"
pkg_ver = "4.7.2"
pkg_dir = pkg_ver + '-$PYTHON'

PREFIX  = pjoin('$SIT_EXTERNAL_SW', "PyQt", pkg_dir)
PYDIR = pjoin("lib", '$PYTHON', "site-packages")
BINDIR = "bin"
PKGINFO = (pkg, pkg_ver, '$PYTHON', '$SIT_ARCH.found')

standardExternalPackage( pkg, **locals() )
