#!/bin/bash 
#
# For all active experiment create missing experiment folders.
#
# Usage: dm_active_exp_folders [-w <wait-secs>]  [-d] [-o]
#    -w <wait-secs>: seconds to wait between checking 
#    -d            : run as daemon 
#    -o            : run cmd only one time
#
# Simple wrapper to run active_exper_status

# set -e
set -u

function run_cmd() {
    while [ 1 ] ; do 
        ${cr_folder} --mkdir --active
        sleep ${wait_time}
    done
}


readonly cr_folder=dm_create_folders

wait_time=120
while getopts :dlow: OPT; do
    case $OPT in
        w|+w) wait_time="$OPTARG" ;;
        d|+d) daemon=1 ;;
        l|+l) uselog=1 ;;
        o|+o) 
            echo "Run only one time"
            ${cr_folder} --mkdir
            exit 
            ;;
        *)
            sed -n -e '2,/^[^#]\|^$/ s/^#//p' $0
            exit 2
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

if [[ ${uselog:-0} -eq 1 ]] ; then
    logfile=/u1/psdm/logs/active_folder.$(date +%Y%m%dT%H%M%S)
    exec &> ${logfile}
fi

[ ${wait_time} -lt 60 ] && echo "wait time to small (<60s)" && exit 1

if [[ ${daemon:-0} -eq 1 ]] ; then
    run_cmd < /dev/null &
else
    run_cmd < /dev/null
fi


