
// *** Do not edit this file, it is auto-generated ***

#include "psddl_pds2psana/pulnix.ddl.h"

#include <cstddef>

#include <stdexcept>

namespace psddl_pds2psana {
namespace Pulnix {
Psana::Pulnix::TM6740ConfigV1::Depth pds_to_psana(Pds::Pulnix::TM6740ConfigV1::Depth e)
{
  return Psana::Pulnix::TM6740ConfigV1::Depth(e);
}

Psana::Pulnix::TM6740ConfigV1::Binning pds_to_psana(Pds::Pulnix::TM6740ConfigV1::Binning e)
{
  return Psana::Pulnix::TM6740ConfigV1::Binning(e);
}

Psana::Pulnix::TM6740ConfigV1::LookupTable pds_to_psana(Pds::Pulnix::TM6740ConfigV1::LookupTable e)
{
  return Psana::Pulnix::TM6740ConfigV1::LookupTable(e);
}

TM6740ConfigV1::TM6740ConfigV1(const boost::shared_ptr<const XtcType>& xtcPtr)
  : Psana::Pulnix::TM6740ConfigV1()
  , m_xtcObj(xtcPtr)
{
}
TM6740ConfigV1::~TM6740ConfigV1()
{
}


uint16_t TM6740ConfigV1::gain_a() const {
  return m_xtcObj->gain_a();
}


uint16_t TM6740ConfigV1::gain_b() const {
  return m_xtcObj->gain_b();
}


uint16_t TM6740ConfigV1::vref() const {
  return m_xtcObj->vref();
}


uint16_t TM6740ConfigV1::shutter_width() const {
  return m_xtcObj->shutter_width();
}


uint8_t TM6740ConfigV1::gain_balance() const {
  return m_xtcObj->gain_balance();
}


Psana::Pulnix::TM6740ConfigV1::Depth TM6740ConfigV1::output_resolution() const {
  return pds_to_psana(m_xtcObj->output_resolution());
}


Psana::Pulnix::TM6740ConfigV1::Binning TM6740ConfigV1::horizontal_binning() const {
  return pds_to_psana(m_xtcObj->horizontal_binning());
}


Psana::Pulnix::TM6740ConfigV1::Binning TM6740ConfigV1::vertical_binning() const {
  return pds_to_psana(m_xtcObj->vertical_binning());
}


Psana::Pulnix::TM6740ConfigV1::LookupTable TM6740ConfigV1::lookuptable_mode() const {
  return pds_to_psana(m_xtcObj->lookuptable_mode());
}


uint8_t TM6740ConfigV1::output_resolution_bits() const {
  return m_xtcObj->output_resolution_bits();
}

Psana::Pulnix::TM6740ConfigV2::Depth pds_to_psana(Pds::Pulnix::TM6740ConfigV2::Depth e)
{
  return Psana::Pulnix::TM6740ConfigV2::Depth(e);
}

Psana::Pulnix::TM6740ConfigV2::Binning pds_to_psana(Pds::Pulnix::TM6740ConfigV2::Binning e)
{
  return Psana::Pulnix::TM6740ConfigV2::Binning(e);
}

Psana::Pulnix::TM6740ConfigV2::LookupTable pds_to_psana(Pds::Pulnix::TM6740ConfigV2::LookupTable e)
{
  return Psana::Pulnix::TM6740ConfigV2::LookupTable(e);
}

TM6740ConfigV2::TM6740ConfigV2(const boost::shared_ptr<const XtcType>& xtcPtr)
  : Psana::Pulnix::TM6740ConfigV2()
  , m_xtcObj(xtcPtr)
{
}
TM6740ConfigV2::~TM6740ConfigV2()
{
}


uint16_t TM6740ConfigV2::gain_a() const {
  return m_xtcObj->gain_a();
}


uint16_t TM6740ConfigV2::gain_b() const {
  return m_xtcObj->gain_b();
}


uint16_t TM6740ConfigV2::vref_a() const {
  return m_xtcObj->vref_a();
}


uint16_t TM6740ConfigV2::vref_b() const {
  return m_xtcObj->vref_b();
}


uint8_t TM6740ConfigV2::gain_balance() const {
  return m_xtcObj->gain_balance();
}


Psana::Pulnix::TM6740ConfigV2::Depth TM6740ConfigV2::output_resolution() const {
  return pds_to_psana(m_xtcObj->output_resolution());
}


Psana::Pulnix::TM6740ConfigV2::Binning TM6740ConfigV2::horizontal_binning() const {
  return pds_to_psana(m_xtcObj->horizontal_binning());
}


Psana::Pulnix::TM6740ConfigV2::Binning TM6740ConfigV2::vertical_binning() const {
  return pds_to_psana(m_xtcObj->vertical_binning());
}


Psana::Pulnix::TM6740ConfigV2::LookupTable TM6740ConfigV2::lookuptable_mode() const {
  return pds_to_psana(m_xtcObj->lookuptable_mode());
}


uint8_t TM6740ConfigV2::output_resolution_bits() const {
  return m_xtcObj->output_resolution_bits();
}

} // namespace Pulnix
} // namespace psddl_pds2psana
