/* Do not edit this file, as it is auto-generated */

#include <boost/python.hpp>
#include <boost/make_shared.hpp>
#include "ndarray/ndarray.h"
#include "pdsdata/xtc/TypeId.hh"
#include "psddl_psana/fli.ddl.h" // inc_psana
#include "psddl_python/Converter.h"
#include "psddl_python/DdlWrapper.h"
#include "psddl_python/ConverterMap.h"
#include "psddl_python/ConverterBoostDef.h"
#include "psddl_python/ConverterBoostDefSharedPtr.h"

namespace psddl_python {
namespace Fli {

using namespace boost::python;
using boost::python::object;
using boost::shared_ptr;
using std::vector;

namespace {
template<typename T, std::vector<int> (T::*MF)() const>
PyObject* method_shape(const T *x) {
  return detail::vintToList((x->*MF)());
}
} // namespace

void createWrappers(PyObject* module) {
  PyObject* submodule = Py_InitModule3( "psana.Fli", 0, "The Python wrapper module for Fli types");
  Py_INCREF(submodule);
  PyModule_AddObject(module, "Fli", submodule);
  scope mod = object(handle<>(borrowed(submodule)));
  {
  scope outer = 
  class_<Psana::Fli::ConfigV1, boost::shared_ptr<Psana::Fli::ConfigV1>, boost::noncopyable >("ConfigV1", no_init)
    .def("width", &Psana::Fli::ConfigV1::width)
    .def("height", &Psana::Fli::ConfigV1::height)
    .def("orgX", &Psana::Fli::ConfigV1::orgX)
    .def("orgY", &Psana::Fli::ConfigV1::orgY)
    .def("binX", &Psana::Fli::ConfigV1::binX)
    .def("binY", &Psana::Fli::ConfigV1::binY)
    .def("exposureTime", &Psana::Fli::ConfigV1::exposureTime)
    .def("coolingTemp", &Psana::Fli::ConfigV1::coolingTemp)
    .def("gainIndex", &Psana::Fli::ConfigV1::gainIndex)
    .def("readoutSpeedIndex", &Psana::Fli::ConfigV1::readoutSpeedIndex)
    .def("exposureEventCode", &Psana::Fli::ConfigV1::exposureEventCode)
    .def("numDelayShots", &Psana::Fli::ConfigV1::numDelayShots)
    .def("frameSize", &Psana::Fli::ConfigV1::frameSize,"Total size in bytes of the Frame object, including image and frame header.")
    .def("numPixelsX", &Psana::Fli::ConfigV1::numPixelsX,"calculate frame X size in pixels based on the current ROI and binning settings")
    .def("numPixelsY", &Psana::Fli::ConfigV1::numPixelsY,"calculate frame Y size in pixels based on the current ROI and binning settings")
    .def("numPixels", &Psana::Fli::ConfigV1::numPixels,"calculate total frame size in pixels based on the current ROI and binning settings")
  ;
  scope().attr("Version")=1;
  scope().attr("TypeId")=int(Pds::TypeId::Id_FliConfig);
  }
  ConverterMap::instance().addConverter(boost::make_shared<ConverterBoostDefSharedPtr<Psana::Fli::ConfigV1> >(Pds::TypeId::Id_FliConfig));

  {
  scope outer = 
  class_<Psana::Fli::FrameV1, boost::shared_ptr<Psana::Fli::FrameV1>, boost::noncopyable >("FrameV1", no_init)
    .def("shotIdStart", &Psana::Fli::FrameV1::shotIdStart)
    .def("readoutTime", &Psana::Fli::FrameV1::readoutTime)
    .def("temperature", &Psana::Fli::FrameV1::temperature)
    .def("data", &Psana::Fli::FrameV1::data)
  ;
  scope().attr("Version")=1;
  scope().attr("TypeId")=int(Pds::TypeId::Id_FliFrame);
  }
  ConverterMap::instance().addConverter(boost::make_shared<ConverterBoostDefSharedPtr<Psana::Fli::FrameV1> >(Pds::TypeId::Id_FliFrame));

  {
    PyObject* unvlist = PyList_New(1);
    PyList_SET_ITEM(unvlist, 0, PyObject_GetAttrString(submodule, "FrameV1"));
    PyObject_SetAttrString(submodule, "Frame", unvlist);
    Py_CLEAR(unvlist);
  }
  {
    PyObject* unvlist = PyList_New(1);
    PyList_SET_ITEM(unvlist, 0, PyObject_GetAttrString(submodule, "ConfigV1"));
    PyObject_SetAttrString(submodule, "Config", unvlist);
    Py_CLEAR(unvlist);
  }
  detail::register_ndarray_to_numpy_cvt<const uint16_t, 2>();

} // createWrappers()
} // namespace Fli
} // namespace psddl_python
