#!/usr/bin/env python 

import sys
import fcntl

"""
Try to aquire a read lock on a file or place an exclusive LOCK on file.

Usage:
  check_for_lock.py <fname>       # try to get shared lock
  check_for_lock.py <fname> lock  # place exclusiv lock (file open in append mode)
  
"""



def main():


    nargs = len(sys.argv) - 1 
    if nargs == 1:
        # check for a file lock
        fp = open(sys.argv[1])
        try:
            fcntl.lockf(fp, fcntl.LOCK_SH | fcntl.LOCK_NB)
        except IOError:
            print "Failed to obtain lock"
        else:
            print "Obtained lock"
            fcntl.lockf(fp, fcntl.LOCK_UN)
        
        fp.close()

    elif nargs == 2 and sys.argv[2] == 'lock':
        fp = open(sys.argv[1], 'a')
        try:
            fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except IOError:
            print "Failed to obtain lock"
        else:
            print "Obtained exclusive lock, hit enter to release lock"
            res = raw_input()
            fcntl.lockf(fp, fcntl.LOCK_UN)
        fp.close()

    else:
        print "wrong lock options"
        




if __name__ == "__main__":

    main()
