#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package bbcp
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any SIT project
Import('*')

from SConsTools.standardExternalPackage import standardExternalPackage

import os

pkg = "pdsh"

PREFIX = os.path.join('$SIT_EXTERNAL_SW', pkg)
BINDIR = "bin"

standardExternalPackage(pkg, **locals())

