#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  SConscript file for package tables
#------------------------------------------------------------------------

# Do not delete following line, it must be present in 
# SConscript file for any LUSI project
Import('*')

from os.path import join as pjoin
from SConsTools.standardExternalPackage import standardExternalPackage

#
# For the standard external packages which contain includes, libraries, 
# and applications it is usually sufficient to call standardExternalPackage()
# giving some or all parameters.
#

pkg = "sip"
pkg_ver = "4.10.1"
PREFIX  = pjoin(env['LUSI_ROOT'], "sw/external", pkg, pkg_ver)

PYDIR = "lib/python"+env['PYTHON_VERSION']+"/site-packages"

BINDIR = "bin"

standardExternalPackage ( pkg, **locals() )

