#ifndef PSDDL_PDS2PSANA_GENERICPGP_DDL_H
#define PSDDL_PDS2PSANA_GENERICPGP_DDL_H 1

// *** Do not edit this file, it is auto-generated ***

#include <vector>
#include <boost/shared_ptr.hpp>
#include "psddl_psana/genericpgp.ddl.h"
#include "pdsdata/psddl/genericpgp.ddl.h"
namespace psddl_pds2psana {
namespace GenericPgp {

class CDimension : public Psana::GenericPgp::CDimension {
public:
  typedef Pds::GenericPgp::CDimension XtcType;
  typedef Psana::GenericPgp::CDimension PsanaType;
  CDimension(const boost::shared_ptr<const XtcType>& xtcPtr);
  virtual ~CDimension();
  virtual uint32_t rows() const;
  virtual uint32_t columns() const;
  const XtcType& _xtcObj() const { return *m_xtcObj; }
private:
  boost::shared_ptr<const XtcType> m_xtcObj;
};

Psana::GenericPgp::CRegister pds_to_psana(Pds::GenericPgp::CRegister pds);

Psana::GenericPgp::CStream pds_to_psana(Pds::GenericPgp::CStream pds);


class ConfigV1 : public Psana::GenericPgp::ConfigV1 {
public:
  typedef Pds::GenericPgp::ConfigV1 XtcType;
  typedef Psana::GenericPgp::ConfigV1 PsanaType;
  ConfigV1(const boost::shared_ptr<const XtcType>& xtcPtr);
  virtual ~ConfigV1();
  virtual uint32_t id() const;
  virtual const Psana::GenericPgp::CDimension& frame_dim() const;
  virtual const Psana::GenericPgp::CDimension& aux_dim() const;
  virtual const Psana::GenericPgp::CDimension& env_dim() const;
  virtual uint32_t number_of_registers() const;
  virtual uint32_t number_of_sequences() const;
  virtual uint32_t number_of_streams() const;
  virtual uint32_t payload_size() const;
  virtual ndarray<const uint32_t, 2> pixel_settings() const;
  virtual ndarray<const uint32_t, 1> sequence_length() const;
  virtual ndarray<const Psana::GenericPgp::CRegister, 1> sequence() const;
  virtual ndarray<const Psana::GenericPgp::CStream, 1> stream() const;
  virtual ndarray<const uint32_t, 1> payload() const;
  virtual uint32_t numberOfRows() const;
  virtual uint32_t numberOfColumns() const;
  virtual uint32_t lastRowExclusions() const;
  virtual uint32_t numberOfAsics() const;
  const XtcType& _xtcObj() const { return *m_xtcObj; }
private:
  boost::shared_ptr<const XtcType> m_xtcObj;
  psddl_pds2psana::GenericPgp::CDimension _frame_dim;
  psddl_pds2psana::GenericPgp::CDimension _aux_dim;
  psddl_pds2psana::GenericPgp::CDimension _env_dim;
  ndarray<Psana::GenericPgp::CRegister, 1> _sequence_ndarray_storage_;
  ndarray<Psana::GenericPgp::CStream, 1> _stream_ndarray_storage_;
};

} // namespace GenericPgp
} // namespace psddl_pds2psana
#endif // PSDDL_PDS2PSANA_GENERICPGP_DDL_H
